name: Deploy Snowflake to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_ADDRESS }} << 'EOF'
            cd /path/to/your/project
            git pull origin main
            # Optionally, restart your service or run additional commands here
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
