name: Deploy Snowflake to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd summer-project-docker-compose/
            cd Snowflake/
            git pull
            cd ..
            docker compose up -d --no-deps --build snowflake
